### ISSUE TITLE
multiples on page?

### ISSUE THREAD

**Issue by sandro-pasquali** [krasimir/demoit#2]
Is there a demo where I have multiple instances of demoit on a page? Something like: https://github.com/FormidableLabs/react-live

**Comment by krasimir** [comment]
I'm working on it and it will be done very soon. I'll post here once it's done.

**Comment by sandro-pasquali** [comment]
Awesome. This is a great project. Let me know if I can help.

**Comment by krasimir** [comment]
Here we go. Demoit is now embedable https://krasimir.github.io/demoit/samples/
